### PR TITLE
fix: update apt source

### PR DESCRIPTION
**Pull request by sbruzzese902**
Hi! 

I was testing your scripts and found an issue with the APT source, which was recently changed.

I propose to follow the [upstream documentation](https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-using-native-package-management) and add a new variable that sets the `KUBERNETES_SHORT_VERSION` to adapt to the upcoming releases.

I hope this helps!

### CODE REVIEW

**Comment by maxdev42** [comment]
Thank you for your contribution which unblocked me personally.
However I have this error now:

`master: + sudo mkdir /etc/apt/keyrings
    master: mkdir: cannot create directory ‘/etc/apt/keyrings’: File exists
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.`

Did you have this problem on your side?

Thanks

**Comment by sbruzzese902** [comment]
Thanks for your comment! I added the `-p` parameter now so the `mkdir` command should not fail if the folder already exists.
Can you try again and let me know?

**Comment by maxdev42** [comment]
It's much better thank you.

The master works fine but node01 blocks on the KUBERNETES_VERSION_SHORT variable, it's quite strange.

`node01: + sudo mkdir -p /etc/apt/keyrings
    node01: + sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    node01: /tmp/vagrant-shell: line 72: KUBERNETES_VERSION_SHORT: unbound variable
    node01: gpg: no valid OpenPGP data found.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.`


Thanks again for the time you spend helping on this project.

**Comment by sbruzzese902** [comment]
Sorry, the new variable was missing in worker nodes.

No problem, I'm happy to help!

**Comment by maxdev42** [comment]
Exactly, thank you for the correction.

Now everything is fine but I get this error at the end:


`==> node01: Waiting for machine to boot. This may take a few minutes...
    node01: SSH address: 127.0.0.1:2200
    node01: SSH username: vagrant
    node01: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.`


The only difference I have with you is the following in the settings.yaml :

`control_ip: 10.0.56.10`

Do you have the same error on your side?

Thank you again for your responsiveness!

**Comment by sbruzzese902** [comment]
No, I didn't get this error...

Can you try to increase the `config.vm.boot_timeout` as suggested by Vagrant itself? 

In the meantime I will try to reproduce the issue.

**Comment by maxdev42** [comment]
I just tried it works thank you very much!

I am very interested in progressing this project too.

I am looking to set up a small infrastructure to host a few sites and test monitoring tools that I know well on a k8s infrastructure.

Would you be interested in developing together on the project?

Thanks to you !

**Comment by techiescamp** [comment]
The repo issue is fixed . We pushed the changes. Also updated the cluster to 1.29 version.

**Pull request merged**
